class_name Ses
extends Node
## Placeholder sound effects (generated by araclar/ses_uret.gd) and haptics.

const NAMES := ["atis", "atis_agir", "carpma_zemin", "carpma_hafif", "carpma_sert", "kirilma", "patlama",
	"totem", "catlama", "kurtarma", "kazanma", "kaybetme"]

var muted := false
var _players := {}
var _last_impact := 0


func _ready() -> void:
	for n in NAMES:
		var p := AudioStreamPlayer.new()
		p.stream = load("res://ses/%s.wav" % n)
		p.max_polyphony = 4
		add_child(p)
		_players[n] = p


func _play(n: String, vol := 1.0, pitch := 1.0) -> void:
	if muted or not _players.has(n):
		return
	var p: AudioStreamPlayer = _players[n]
	p.volume_db = linear_to_db(maxf(0.001, vol))
	p.pitch_scale = pitch
	p.play()


func fire(type: String) -> void:
	_play("atis_agir" if type == "heavy" else "atis")


func impact(force: float, ground: bool) -> void:
	var now := Time.get_ticks_msec()
	if now - _last_impact < 45:
		return
	_last_impact = now
	var k := minf(1.0, force / 350.0)
	if ground:
		_play("carpma_zemin", 0.5 + k * 0.5)
	else:
		_play("carpma_sert" if k > 0.5 else "carpma_hafif", 0.6 + k * 0.4, randf_range(0.9, 1.15))


func shatter(vol := 1.0) -> void:
	_play("kirilma", vol, randf_range(0.95, 1.1))


func explode() -> void:
	_play("patlama")


func totem() -> void:
	_play("totem")


func crack() -> void:
	_play("catlama")


func rescue() -> void:
	_play("kurtarma")


func win() -> void:
	_play("kazanma")


func lose() -> void:
	_play("kaybetme")


## Short haptic tap (iPhone: Core Haptics, Android: vibration motor).
static func vibrate(ms: int, amplitude := 0.6) -> void:
	Input.vibrate_handheld(ms, amplitude)
