import { chromium } from 'playwright-core';
import path from 'node:path';
const exe = '/opt/pw-browsers/chromium-1194/chrome-linux/chrome';
const browser = await chromium.launch({ executablePath: exe, args: ['--use-angle=swiftshader', '--enable-unsafe-swiftshader', '--ignore-gpu-blocklist'] });
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true });
const page = await ctx.newPage();
const errors = [];
page.on('console', (m) => { if (m.type() === 'error' || m.type() === 'warning') errors.push(m.type() + ': ' + m.text()); });
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
await page.goto('file://' + path.resolve('dist/test.html'));
await page.waitForFunction(() => !document.getElementById('scrStart').hidden || !document.getElementById('scrError').hidden, null, { timeout: 30000 });
await page.screenshot({ path: 'out/01-start.png' });
const which = process.argv[2] || 'shots';
await page.evaluate(() => window.__buzkiran.startLevel(1, '3d'));
await page.waitForTimeout(400);
await page.screenshot({ path: 'out/02-l4-3d.png' });
await page.evaluate(() => window.__buzkiran.startLevel(4, '25d'));
await page.waitForTimeout(400);
await page.screenshot({ path: 'out/03-l4-25d.png' });
await page.evaluate(() => window.__buzkiran.startLevel(8, '3d'));
await page.waitForTimeout(400);
await page.screenshot({ path: 'out/04-l8-3d.png' });
await page.evaluate(() => window.__buzkiran.startLevel(8, '25d'));
await page.waitForTimeout(400);
await page.screenshot({ path: 'out/05-l8-25d.png' });
console.log('measure L8 25d', JSON.stringify(await page.evaluate(() => window.__buzkiran.measure())));
console.log(errors.length ? errors.join('\n') : 'no console errors');
await browser.close();
