extends SceneTree
## Records numeric shot inputs and expected hashes for the cross-device
## self-test (res://sim/referans.gd), from the bot's solutions.
## Usage: godot --headless -s res://araclar/referans_uret.gd -- bot1.json [bot2.json ...]

const EVERY := 30


func _init() -> void:
	var sols := {}
	for path in OS.get_cmdline_user_args():
		var rep: Dictionary = JSON.parse_string(FileAccess.get_file_as_string(path))
		for e in rep.levels:
			if e.solution.shots == null:
				push_error("B%d icin cozum yok" % e.level)
				quit(1)
				return
			sols[int(e.level)] = e.solution.sequence.map(func(s): return {"t": s.t, "a": int(s.a), "b": int(s.b)})
	var cases: Array = []
	for id in range(1, 11):
		cases.append({"name": "B%d kazanan" % id, "level": id, "shots": sols[id]})
	# a miss first, then the known solution (level 10 has a spare normal ball)
	var lv10 := Levels.by_id(10)
	var miss = null
	for cand in [{"t": "normal", "a": 150, "b": 50}, {"t": "normal", "a": 150, "b": 700}, {"t": "normal", "a": 0, "b": 50}, {"t": "normal", "a": -150, "b": 700}]:
		var s := Sim.new(lv10)
		s.run_shot(cand.a, cand.b, cand.t)
		var untouched: bool = s.cages_left() == lv10.cages.size() and s.totems_left() == lv10.totems.size() and s.nests_broken() == 0
		for sh in sols[10]:
			s.run_shot(sh.a, sh.b, sh.t)
		var ok: bool = untouched and s.phase == "won"
		s.free_all()
		if ok:
			miss = cand
			break
	if miss == null:
		push_error("B10 icin temiz iska bulunamadi")
		quit(1)
		return
	cases.append({"name": "B10 ıska + çözüm", "level": 10, "shots": [miss] + sols[10]})
	# an ember that cracks the nest (protect goal failure path)
	var lv8 := Levels.by_id(8)
	for b in range(50, 401, 10):
		var s := Sim.new(lv8)
		s.run_shot(0, b, "ember")
		var broke := s.nests_broken() > 0
		s.free_all()
		if broke:
			cases.append({"name": "B8 yuva kırılır", "level": 8, "shots": [{"t": "ember", "a": 0, "b": b}]})
			break
	var won := 0
	for c in cases:
		var r := Sim.replay(Levels.by_id(c.level), c.shots, EVERY)
		c.expect = {"initial": r.initial, "ready": r.ready, "checkpoints": r.checkpoints, "shot_steps": r.shot_steps,
			"final_step": r.final_step, "final": r.final, "phase": r.phase}
		if r.phase == "won":
			won += 1
		print("%-18s %s faz=%s adim=%d son=%s" % [c.name, JSON.stringify(c.shots), r.phase, r.final_step, r.final])
	var meta := {"every": EVERY, "engine": "Godot %s + Rapier3D %s" % [Engine.get_version_info().string, "0.35.4"],
		"recorded_on": "%s %s (bulut, masaüstü işlemci)" % [OS.get_name(), Engine.get_architecture_name()],
		"recorded_at": Time.get_datetime_string_from_system(true)}
	var src := "class_name Referans\n## Generated by araclar/referans_uret.gd. Numeric shot inputs and expected state hashes.\nconst DATA := " + JSON.stringify({"meta": meta, "cases": cases}) + "\n"
	var f := FileAccess.open("res://sim/referans.gd", FileAccess.WRITE)
	f.store_string(src)
	print("vaka ", cases.size(), " kazanan ", won)
	quit()
